### ISSUE TITLE
BGP attribute NEXT_HOP - KeyError: 32

### ISSUE THREAD

**Issue by mikolaj-kow** [OpenBMP/openbmp-mrt2bmp#12]
Greetings, 
when selecting RIPE server (tested with rrc00 and rrc23), there is following error. 

How I can debug this further? 

```
/usr/bin/openbmp-mrt2bmp -c /etc/openbmp-mrt2bmp.yml --rp rrc23.ripe.net
Ripe is chosen...
openbmp-mrt2bmp_rrc23.ripe.net.log
<type 'exceptions.KeyError'>
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtProcessors.py", line 606, in run
    rp.processRouteView(is_first_run)
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtProcessors.py", line 526, in processRouteView
    rp.processRibFile()
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtProcessors.py", line 68, in processRibFile
    for m in mp:
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtParser.py", line 118, in next
    self.parseMrtEntry( entry['mrt_entry'], msg_len, msg_type, msg_subtype)
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtParser.py", line 165, in parseMrtEntry
    self.parseTableDumpV2(buf, mrt_message, msg_len, msg_type, msg_subtype)
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtParser.py", line 244, in parseTableDumpV2
    self.parseRibEntries(buf[p:], mrt_message['rib_entries'], address_family, safi, raw_nlri)
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtParser.py", line 388, in parseRibEntries
    rib_entry['raw_bgp_attributes'], rib_entry['attribute_length'], address_family, safi, raw_nlri, rib_entry['raw_mp_reach_nlri'])
  File "build/bdist.linux-x86_64/egg/openbmp/mrt2bmp/MrtParser.py", line 425, in parseBgpAttributes
    if BGP_ATTRIBUTES[bgp_path_attribute['type']] == 'NEXT_HOP':
KeyError: 32
```

**Comment by mikolaj-kow** [comment]
In the log there is nothing much 

```
2020-01-23 16:04:32,361 | INFO     | mrt_processors | - rrc23.ripe.net is started
2020-01-23 16:04:54,208 | INFO     | router_processor | -- 2020.01/RIBS/bview.20200123.0800.gz is started
2020-01-23 16:04:54,211 | INFO     | bmp_writer | Running bmp_writer
2020-01-23 16:04:54,213 | INFO     | bmp_writer | Connected to remote collector: 172.17.0.3:5000
2020-01-23 16:09:07,677 | INFO     | bmp_writer | rewrite stopped
```
